name: Business Queries CI Pipeline

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test the python script 'lambda_function.py' can run
        run : python BusinessQueries/lambda_function.py

      - name: Lint the code
        run: flake8 BusinessQueries/lambda_function.py

      - name: Unit testing
        run: python -m unittest "queries_unit_tests.py"
      
      - name: Job Stats
        run: echo "🍏 This job's status is ${{ job.status }}."
